// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ClearcartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void clearcart() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(1025, 699));
    {
      WebElement element = driver.findElement(By.cssSelector(".header-cart__trigger"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".header-cart__trigger")).click();
    js.executeScript("window.scrollTo(0,17.200000762939453)");
    js.executeScript("window.scrollTo(0,169.60000610351562)");
    js.executeScript("window.scrollTo(0,1373.199951171875)");
    {
      WebElement element = driver.findElement(By.cssSelector(".sc-product:nth-child(5) .sc-remove-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".sc-product:nth-child(5) .sc-remove-item")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".signin-form__submit")).click();
    js.executeScript("window.scrollTo(0,1058.800048828125)");
    driver.findElement(By.cssSelector(".sc-product:nth-child(3) .sc-remove-item")).click();
    driver.findElement(By.cssSelector(".signin-form__submit")).click();
    js.executeScript("window.scrollTo(0,680)");
    driver.findElement(By.cssSelector(".sc-remove-item")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".signin-form__submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".signin-form__submit")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".page-header__account-button")).click();
    driver.findElement(By.cssSelector(".header-cart__checkout")).click();
    driver.close();
    {
      WebElement element = driver.findElement(By.cssSelector(".header-cart__trigger"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".header-cart__trigger")).click();
    js.executeScript("window.scrollTo(0,237.1999969482422)");
    driver.findElement(By.cssSelector(".sc-remove-item")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".signin-form__submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".signin-form__submit")).click();
    driver.findElement(By.cssSelector(".page-header__account-button")).click();
    driver.findElement(By.cssSelector(".header-account-icon__dropdown-item-button")).click();
    driver.findElement(By.cssSelector(".header-account-icon__dropdown-item-button")).click();
    driver.findElement(By.cssSelector(".header-search__input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".selected .autocomplete-product-grid-name"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".full-image__img > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    js.executeScript("window.scrollTo(0,810.4000244140625)");
    driver.findElement(By.cssSelector(".add-cart")).click();
    js.executeScript("window.scrollTo(0,1044.199951171875)");
    js.executeScript("window.scrollTo(0,819.4000244140625)");
    driver.findElement(By.cssSelector(".add-cart > span")).click();
    driver.findElement(By.cssSelector(".option-tiles__item:nth-child(5) > .option-tiles__item-title")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".add-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".add-cart")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".add-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".header-cart__trigger")).click();
    js.executeScript("window.scrollTo(0,19.600000381469727)");
    {
      WebElement element = driver.findElement(By.cssSelector(".sc-remove-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".sc-remove-item")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".signin-form__submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
