// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginproperlyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginproperly() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(703, 864));
    driver.findElement(By.cssSelector(".page-header__account-button")).click();
    driver.findElement(By.cssSelector(".header-account-icon__dropdown-item-sign-in")).click();
    driver.findElement(By.cssSelector("#gigya-login-form .gigya-input-text")).click();
    driver.findElement(By.cssSelector(".gigya-valid")).sendKeys("kunal.dhawan10@outlook.com");
    driver.findElement(By.cssSelector(".pwd-show-hide-btn")).click();
    driver.findElement(By.cssSelector("#gigya-login-form .gigya-composite-control-submit > .gigya-input-submit")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".loyalty-signup__option-img_mastercard"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".mfp-close:nth-child(3)")).click();
  }
}
