// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registration() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(703, 864));
    driver.findElement(By.cssSelector(".page-header__account-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".full-image__img > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".header-account-icon__dropdown-item-register"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".header-account-icon__dropdown-item-register")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#register-site-login .gigya-input-text")).click();
    driver.findElement(By.cssSelector(".gigya-valid")).sendKeys("kunal.dhawan10@outlook.com");
    driver.findElement(By.cssSelector(".visible")).click();
    driver.findElement(By.cssSelector(".gigya-valid:nth-child(2)")).sendKeys("Check&08");
    driver.findElement(By.id("gigya-password-90574179967216050")).click();
    driver.findElement(By.cssSelector(".gigya-composite-control:nth-child(2) > .pwd-show-hide-btn")).click();
    driver.findElement(By.cssSelector(".ciam-consent-visible > .gigya-label")).click();
    driver.findElement(By.id("gigya-password-90574179967216050")).click();
    driver.findElement(By.cssSelector("#register-site-login .gigya-input-submit")).click();
    driver.findElement(By.cssSelector(".loyalty-signup__skip-loyalty")).click();
  }
}
